name: zizo_radar
description: Network Scanner App
publish_to: 'none'
version: 1.3.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^5.0.0
  dart_ping: ^9.0.1 # المكتبة الجديدة للصيد الحقيقي

dev_dependencies:
  flutter_test:
    sdk: flutter
  # المكتبة اللي راح تسوي الأيقونة
  flutter_launcher_icons: ^0.13.1

# إعدادات الأيقونة
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "scan.png" # لأنك حطيتها بالمجلد الرئيسي مباشرة
  min_sdk_android: 21

flutter:
  uses-material-design: true
