name: scron Build System 🚀

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Fix Native Files
        run: flutter create --project-name=scron . --platforms android

      - name: Get Dependencies
        run: flutter pub get
      
      - name: Generate Icons
        run: dart run flutter_launcher_icons
      
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Scron-Final-App
          path: build/app/outputs/flutter-apk/app-release.apk
