name: scron Build System 🚀

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      # 1. توليد الملفات
      - name: Fix Native Files
        run: flutter create --project-name=scron . --platforms android

      # 2. حقن المانيفست بأيقونة "نظام" افتراضية لتجنب خطأ الـ Resource
      - name: Force Internet Permission
        run: |
          cat <<EOF > android/app/src/main/AndroidManifest.xml
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET" />
              <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
              <application
                  android:label="scron"
                  android:name="\${applicationName}"
                  android:icon="@android:drawable/sym_def_app_icon">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <meta-data
                        android:name="io.flutter.embedding.android.NormalTheme"
                        android:resource="@style/NormalTheme"
                        />
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2" />
              </application>
          </manifest>
          EOF

      - name: Get Dependencies
        run: flutter pub get
      
      # 3. البناء بدون توليد أيقونات حالياً (حتى نضمن وصول الإنترنت أولاً)
      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Scron-Final-APKs
          path: build/app/outputs/flutter-apk/*.apk
